# Site
name: "Wire Engineering"
title: "Wire Engineering"
description: "Welcome to Wire Engineering. We are strong believers of Open Source and Knowledge Sharing. Here you will find content about software engineering, problem solving and experiences."
meta_description: "Welcome to Wire Engineering. We are strong believers of Open Source and Knowledge Sharing. Here you will find content about software engineering, problem solving and experiences."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 8
baseurl: ''
email: 'fernando@wire.com'
google_analytics: ''
disqus: ''
sharethis: ''

# Authors
authors:
  wire:
    name: Wire Engineering
    display_name: Wire Engineering
    gravatar: ec53eaa4d47c6532d534864aa84531a2
    email: fernando@wire.com
    web: https://wire.engineering
    description: "The most secure collaboration platform."

  fernando:
    name: Fernando Cejas
    display_name: Fernando Cejas
    gravatar: 12defde716586eb2d726d081a161756d
    email: fernando@wire.com
    web: https://www.fernandocejas.com
    twitter: https://twitter.com/fernando_cejas
    description: "Director of Mobile @Wire. Nerdy, huge fan of Open Source and knowledge sharing. Speaker. I love Scalability, Quantum Computing, Mobile Development and Software Engineering in general."

  bradley:
    name: Bradley Wilson
    display_name: Bradley Wilson
    gravatar: 42952016f8d187247af3e0cb3b24f94e
    email: bradley@wire.com
    web: https://github.com/BradleyWire
    description: "Bradley has been an Android engineer for 4 years professionally and works with Java, Kotlin and Python. With previous experience leading a team in a large UK bank. He specialises in refactoring legacy codebases to follow clean architectural principles/design, developing apps that are accessible by all and lives by the philosophy that if it isn't tested its broken."
    
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge
